### ISSUE TITLE
Katalóg požiadaviek

### ISSUE THREAD

**Issue by babalsim** [TIS2019-FMFI/fitness#1]

**Comment by pavelpetrovic** [comment]
dakujem za aktualizaciu KP. tu su moje strucne komentare, prosim, vsetky zapracujte a novu verziu mi co najskor poslite, aby som ju znovu skontroloval este raz pred tym, ako KP poslete zadavatelke.

* prosim dajte pozor na hrubky, napr. "bude závislí", "Rýchli prístup", "klientov, ktorý"
* v tomto dokumente prosim odstrante z cislovania "1." pri vsetkych castiach - tak to bude az vo finalnej technickej dokumentacii, ale toto je KP, kde by mali byt cisla casti 1, 2 a 3.
* z popisu v 2. casti ani z poziadaviek mi nie je jasne, ci system bude fungovat naraz iba z jedneho pocitaca, alebo ci bude zvladat aj situaciu, keby z dvoch pocitacov pristupoval do DB sucasne
* ak system bezi na webe, nemal by sa pouzivatel prihlasovat cez nejaky ucet?
* vsetky poziadavky v casti 3 maju byt pisane ako hodnota, ktoru aplikacia poskytuje pre pouzivatela, t.j. napr. namiesto "Rýchle vyhľadávanie klientov v databáze podľa mena, priezviska alebo telefónneho čísla." treba napisat "Aplikacia umoznuje rýchle vyhľadanie klienta v databáze podľa mena, priezviska alebo telefónneho čísla." => ale aj to by malo byt upresnene, ci treba zadat cely presny udaj, alebo staci aj napr. cast mena alebo priezviska. Co sa stane, ak je viac klientov s rovnakym menom alebo priezviskom? Je mozne vyhladavat aj zadanim mena aj priezviska? Dokument ma byt jednoznacny.
* "Pridávanie klientov, ktorý sa budú môcť následne dať nastaviť ako objednávatelia aktivít a
vyhľadávať v systéme." => to znie ako keby ti klienti mohli v systeme nieco vyhladavat, formulujte presne a jednoznacne; Nie je jasne, co znamena "nastavit ako objednavatelia". Mozu byt aj klienti, ktori nie su objednavatelia? ak nie, tak aky to ma zmysel nastavovat ich ako objednavatelov? 
a pripominam, ze vsetky poziadavky maju byt formulovane ako nieco, co aplikacia robi, umoznuje, zabezpecuje, eviduje, atd...  jednoducho robi nieco, z coho ma pouzivatel nejaku hodnotu, tyka sa to aj vsetkych dalsich poziadaviek.
* R03 Odstraňovanie klientov => kombinovane poziadavky. jedna vec je vymazanie, druha vec je nastavit neaktivny, tretia vec je aktivovat neaktivneho. ako sa to urobi?
* R05, R10-R12: tieto poziadavky su prazdne. Kazda poziadavka je formulovana celymi vetami. Nadpis poziadavky nepotrebujem, ale potrebujem text poziadavky. Treba to vsetko podrobne rozpisat. Co vsetko bude mozne v aplikacii prezerat a ako.
* vyjadrite sa, prosim, niekde k tomu, ci bude aplikacia responzivna (vzhladom na zmenu velkosti okna prehliadaca), resp. ci ma naroky na nejake minimalne rozlisenie obrazovky

dakujem.

**Comment by babalsim** [comment]
> dakujem za aktualizaciu KP. tu su moje strucne komentare, prosim, vsetky zapracujte a novu verziu mi co najskor poslite, aby som ju znovu skontroloval este raz pred tym, ako KP poslete zadavatelke.
> 
> * prosim dajte pozor na hrubky, napr. "bude závislí", "Rýchli prístup", "klientov, ktorý"
> * v tomto dokumente prosim odstrante z cislovania "1." pri vsetkych castiach - tak to bude az vo finalnej technickej dokumentacii, ale toto je KP, kde by mali byt cisla casti 1, 2 a 3.
> * z popisu v 2. casti ani z poziadaviek mi nie je jasne, ci system bude fungovat naraz iba z jedneho pocitaca, alebo ci bude zvladat aj situaciu, keby z dvoch pocitacov pristupoval do DB sucasne
> * ak system bezi na webe, nemal by sa pouzivatel prihlasovat cez nejaky ucet?
> * vsetky poziadavky v casti 3 maju byt pisane ako hodnota, ktoru aplikacia poskytuje pre pouzivatela, t.j. napr. namiesto "Rýchle vyhľadávanie klientov v databáze podľa mena, priezviska alebo telefónneho čísla." treba napisat "Aplikacia umoznuje rýchle vyhľadanie klienta v databáze podľa mena, priezviska alebo telefónneho čísla." => ale aj to by malo byt upresnene, ci treba zadat cely presny udaj, alebo staci aj napr. cast mena alebo priezviska. Co sa stane, ak je viac klientov s rovnakym menom alebo priezviskom? Je mozne vyhladavat aj zadanim mena aj priezviska? Dokument ma byt jednoznacny.
> * "Pridávanie klientov, ktorý sa budú môcť následne dať nastaviť ako objednávatelia aktivít a
>   vyhľadávať v systéme." => to znie ako keby ti klienti mohli v systeme nieco vyhladavat, formulujte presne a jednoznacne; Nie je jasne, co znamena "nastavit ako objednavatelia". Mozu byt aj klienti, ktori nie su objednavatelia? ak nie, tak aky to ma zmysel nastavovat ich ako objednavatelov?
>   a pripominam, ze vsetky poziadavky maju byt formulovane ako nieco, co aplikacia robi, umoznuje, zabezpecuje, eviduje, atd...  jednoducho robi nieco, z coho ma pouzivatel nejaku hodnotu, tyka sa to aj vsetkych dalsich poziadaviek.
> * R03 Odstraňovanie klientov => kombinovane poziadavky. jedna vec je vymazanie, druha vec je nastavit neaktivny, tretia vec je aktivovat neaktivneho. ako sa to urobi?
> * R05, R10-R12: tieto poziadavky su prazdne. Kazda poziadavka je formulovana celymi vetami. Nadpis poziadavky nepotrebujem, ale potrebujem text poziadavky. Treba to vsetko podrobne rozpisat. Co vsetko bude mozne v aplikacii prezerat a ako.
> * vyjadrite sa, prosim, niekde k tomu, ci bude aplikacia responzivna (vzhladom na zmenu velkosti okna prehliadaca), resp. ci ma naroky na nejake minimalne rozlisenie obrazovky
> 
> dakujem.

Urobil som potrebne zmeny a doplnil som niekolko poziadaviek po stretnuti so zadavatelkou vo fitness centre. Tu je [link](https://github.com/TIS2019-FMFI/fitness/blob/requirements/requirements.pdf) na novu verziu. @pavelpetrovic

**Comment by pavelpetrovic** [comment]
- preco je obsah pred nadpisom?
- do 1.1. mozete uviest aj: je zavazny pre obe strany, pouzije sa na vyhodnotenie spravnosti implementacie
- R01 ak idete prog. aj fulltextove, prosim uvedte to aj v KP
   co sa stane po vyhladani klienta? a co potom tam moze robit?

ked vsetky drobnosti zapracujete a niekto to este raz u vas skontroluje, tak KP prosim poslat zadavatelom, aby si tuto vyslednu verziu este raz dokladne prestudovali, lebo podla nej budete system navrhovat.

- R03: prosim uviest informaciu o  nasledkoch (napr. aktualne platne rezervacie, ...)
- R04: prosim uviest info o nasledkoch
- R07: toto miesto je dobre miesto na rozpisanie, co presne sa o klientovi eviduje
- R08: cas -> okno casu. +  kazdej rezervecii prislucha prave jedno okno casu
- R17: prosim pridat kratke info o tom, ci sa prihlasuje ako meno/heslo alebo mail/heslo, alebo iba heslo
- zvazte pridat poziadavku o vytvarani zaznamu zmien udajov a nejakej moznosti sa tam pozriet (hoci aj rucne na servri, prip. jedno tlacidlo na view plain text...)

**Comment by babalsim** [comment]
Katalog poziadaviek je upraveny podla https://github.com/TIS2019-FMFI/fitness/issues/1#issuecomment-550981262
@pavelpetrovic
