### ISSUE TITLE
Návrh D

### ISSUE THREAD

**Issue by RichardDominik** [TIS2019-FMFI/fitness#12]
D. Zrozumiteľný a jednoznačný návrh implementácie, podľa ktorého sa dá aplikácia vyvinúť a ktorý bude obsahovať: UML component diagram, UML class diagram, a aspoň jeden z dvojice UML state a UML sequence diagram, zrozumiteľne vysvetlenú architektúru, rozdelenie na časti (moduly) a ich interfejsy, využité technológie, cieľové prostredie nasadenia do prevádzky.

**Comment by NicolasOrsag** [comment]
Conpoment diagram hotovo

**Comment by NicolasOrsag** [comment]
Diagram komponentov - hotovo

**Comment by pavelpetrovic** [comment]
ku stavovemu diagramu:
  - kazdy stavovy prechod by mal mat popis:  pri akej udalosti, akcii alebo po akom case k prechodu dochadza
 - preco je add stav a update nie je stav (rezervacie)

**Comment by pavelpetrovic** [comment]
ku komponentnemu diagramu:
  - prosim aspon kratky vysvetlujuci text do navrhu
    (co ktory komponent je a ma na starosti, interfaces medzi komponentnami by mali byt tiez rozpisane - aby ste ich mohli podla navrhu nezavisle implementovat)
  - legenda by pomohla
  - UI rozhrania su rucicky, nemali by byt kruzky?
inak je krasny a schvalujem ho
