### ISSUE TITLE
Public endopoint for orders 

### ISSUE THREAD

**Issue by RichardDominik** [TIS2019-FMFI/fitness#63]
Vytvorit verejny endpoint pre ludi ktory maju zaujem vidiet ktore stroje su obsadene v akom case 

podla poziadaviek @beowulf11  by mali byt 2 endopointy, jeden na vsetky stroje a procedury a druhy na casy objednavok (neposielat gdrp udaje ako meno kto to ma rezervovane)

**Comment by babalsim** [comment]
@beowulf11 mohol by si mi prosim blizsie specifikovat, ake data ti mam presne vracat cez tie endpointy?

**Comment by pavelpetrovic** [comment]
nebudem tajiť, že na toto bol určený dokument návrh :)
